### PR TITLE
cmake-native: remove unnecessary patch and bbappend

### PR DESCRIPTION
**Pull request by jackmitch**
The patch has been upstream and is no longer required as of the
following commit.

commit 7a3db344543d3cf9d16640c4cff6084049bf3aca
Author: Alexander Kanavin <alex.kanavin@gmail.com>
Date:   Sun Aug 23 22:20:29 2020 +0200

    cmake: update 3.17.3 -> 3.18.1

Signed-off-by: Jack Mitchell <ml@embed.me.uk>

### CODE REVIEW

**Comment by jackmitch** [comment]
It may be worthwhile branching for older releases which still require the patch.

**Comment by gpanders** [comment]
Can you also remove the CMake section in the README as well?

**Comment by jackmitch** [comment]
Done

**Comment by gpanders** [comment]
Thanks!

**Pull request merged**
